package Vistas.MenuPrincipal;
import javax.swing.JDesktopPane;

public class FrmPrincipal extends  javax.swing.JFrame {
    public GestorVistaPrincipal gestorVista;
 
    
    public FrmPrincipal() {
        initComponents();
    }

    public FrmPrincipal(GestorVistaPrincipal aThis) {
        initComponents();
        gestorVista=aThis;
    }


    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jmenu = new javax.swing.JMenuBar();
        mnConfiguracion = new javax.swing.JMenu();
        MiMarca = new javax.swing.JMenuItem();
        mnuItemModelo = new javax.swing.JMenuItem();
        mnuItemCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo");

        jmenu.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N

        mnConfiguracion.setText("Configuración");
        mnConfiguracion.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        mnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConfiguracionActionPerformed(evt);
            }
        });

        MiMarca.setLabel("Marca");
        MiMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoMarcaActionPerformed(evt);
            }
        });
        mnConfiguracion.add(MiMarca);

        mnuItemModelo.setText("Modelo");
        mnuItemModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemModeloActionPerformed(evt);
            }
        });
        mnConfiguracion.add(mnuItemModelo);

        mnuItemCliente.setText("Cliente");
        mnuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemClienteActionPerformed(evt);
            }
        });
        mnConfiguracion.add(mnuItemCliente);

        jmenu.add(mnConfiguracion);

        setJMenuBar(jmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTipoMarcaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.gestorVista.abrirMarca(getEscritorio());
    }                                               

    /*
    private void mnuTipoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoMarcaActionPerformed
        this.gestorVista.abrirMarca(getEscritorio());
    }//GEN-LAST:event_mnuTipoMarcaActionPerformed

    */
    private void mnuItemModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemModeloActionPerformed
       this.gestorVista.abrirModelo(getEscritorio());
    }//GEN-LAST:event_mnuItemModeloActionPerformed

    private void mnuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemClienteActionPerformed
       this.gestorVista.abrirCliente(getEscritorio());
    }//GEN-LAST:event_mnuItemClienteActionPerformed

    private void mnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConfiguracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnConfiguracionActionPerformed

    
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MiMarca;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jmenu;
    private javax.swing.JMenu mnConfiguracion;
    private javax.swing.JMenuItem mnuItemCliente;
    private javax.swing.JMenuItem mnuItemModelo;
    // End of variables declaration//GEN-END:variables

}
